FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY . .

RUN dotnet new sln -n OuterloopLabApi --format sln --force
RUN dotnet sln OuterloopLabApi.sln add OuterloopLabApi/OuterloopLabApi.csproj

RUN dotnet restore OuterloopLabApi.sln
RUN dotnet publish OuterloopLabApi.sln -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

EXPOSE 3000
ENTRYPOINT ["dotnet", "OuterloopLabApi.dll"]
